version: "3"

services:
  api-proyecto:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-proyecto
    container_name: api
    restart: unless-stopped
    ports:
      - "81:81"
    volumes:
      - .:/home/node/app
